### ISSUE TITLE
read this

### ISSUE THREAD

**Issue by Krzx1337** [Gowixx/SpotifyGenerator#1]
Dear gowixx,
today i was lurking github.com and came accross your github repo i decided to click on it little did i know i was clicking on a spotify account generator this is classed as automating/abusing spotifys api! this however is against spotifys terms of service in this case i am going to be sueing you for $30,000 for the damage and destruction you caused,

regards
Krzx

**Comment by uhIgnacio** [comment]
shut up krzx

**Comment by Krzx1337** [comment]
shut up igna  or faith i forgot and cba checking

**Comment by uhIgnacio** [comment]
faith is the worst skid
im igna the best skid

**Comment by Gowixx** [comment]
tf

**Comment by Krzx1337** [comment]
oh its igna hiii
