### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by TheOPtimal** [Gowixx/SpotifyGenerator#3]
Use GPLv3 so skids can't paste it

**Comment by Gowixx** [comment]
wtf, you exist?

**Comment by Gowixx** [comment]
Done

**Comment by TheOPtimal** [comment]
> wtf, you exist?

how have you been man?

**Comment by Gowixx** [comment]
good hub, whats ur contact

**Comment by Gowixx** [comment]
hbu*

**Comment by TheOPtimal** [comment]
i don't use discord anymore, since its gone to shit. I use a platform called element. just register on https://element.io and tell me your username

**Comment by Krzx1337** [comment]
@Gowixx i am big fan

**Comment by Krzx1337** [comment]
i even skidded your tools

**Comment by Gowixx** [comment]
thanks man

**Comment by Francesco2426** [comment]
> i don't use discord anymore, since its gone to shit. I use a platform called matrix. just register on https://element.io and tell me your username

didnt you try and get splat to eat cyanide?

**Comment by TheOPtimal** [comment]
> > i don't use discord anymore, since its gone to shit. I use a platform called matrix. just register on [element.io](https://element.io) and tell me your username
> 
> didnt you try and get splat to eat cyanide?

no i told him to eat cherry pits

**Comment by Francesco2426** [comment]
which literally has cyanide

**Comment by Gowixx** [comment]
ignore the facts smh

**Comment by TheOPtimal** [comment]
> which literally has cyanide

way to be a buzzkill man

**Comment by Francesco2426** [comment]
ok clown

**Comment by blade2poor** [comment]
i enjoy listening to your conversations

**Comment by tcrms** [comment]
> i enjoy listening to your conversations
💀
